import { cn } from "@/lib/utils";
import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { cookies } from "next/headers";
import Script from "next/script";
import GoogleOneTap from "@/components/GoogleOneTap";
import SessionWrapper from "@/components/SessionWrapper";
import { Toaster } from "@/components/ui/sonner";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // Server side fetch example
  fetch('http://localhost:5005/auction', {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
      'Cookie': cookies().toString() // Send cookies with jwt token
    }
  }).then(response => response.json())

  return (
    <html lang="en" className="min-h-[100%]">
      <Script
        src="https://accounts.google.com/gsi/client"
        strategy="afterInteractive"
      />
      <body className={cn(montserrat.className, "bg-background", "min-h-[100vh] max-w-screen-xl m-auto")}>
        <SessionWrapper>
          <GoogleOneTap />
        </SessionWrapper>
        {children}
        <Toaster richColors  />
      </body>
    </html>
  );
}
